### ISSUE TITLE
엑스박스가 뜨는 버그가 있습니다

### ISSUE THREAD

**Issue by nx006** [loosie/github-readme-tistory-card#4]
저만 이런 건가 싶어서 다른 사람들이 사용한 것도 보았는데, 똑같이 엑스박스로 뜨고 있습니다. 제 노트북 환경 외에 다른 환경에서 이렇게 뜨는 지는 확인하지 못 했습니다.

<img width="196" alt="스크린샷 2023-05-09 오후 11 13 39" src="https://github.com/loosie/github-readme-tistory-card/assets/103521468/586065aa-acea-4ce5-bcdf-175a58eafdfd">

사용한 코드 방식:
```
    <img src="https://github-readme-tistory-card.vercel.app/api?name=nx006" alt="Tistory Post">
```

또한 다음과 같이 직접 `postId=default`로 설정해두어도, 여전히 오작동합니다.
```
    <img src="https://github-readme-tistory-card.vercel.app/api?name=nx006&postId=default" alt="Tistory Post">
```

재밌는 점은, 만약 제가 `postId=28` 이런 식으로 직접 제공한다면, 이건 또 뜹니다.
바로 아래 코드처럼요:
```
    <img src="https://github-readme-tistory-card.vercel.app/api?name=nx006&postId=28" alt="Tistory Post">
```

<img width="1098" alt="스크린샷 2023-05-09 오후 11 15 49" src="https://github.com/loosie/github-readme-tistory-card/assets/103521468/5fd7f6ba-8837-49bf-84c6-d7a136b8b9db">

그런데 모든 postId에 뜨는 건 아니고, 최신 post인 postId=29를 넣어봤는데, 이건 또 안 됩니다(postId=19는 존재합니다).

<img width="1058" alt="스크린샷 2023-05-09 오후 11 18 34" src="https://github.com/loosie/github-readme-tistory-card/assets/103521468/2f28e928-328b-44ef-8944-0e25b77040f0">

즉 종합적으로 봤을 때 가장 최신 포스트를 불러오는데 무엇인가 문제가 있어 보입니다. postId를 최신이 아닌 유효한 다른 포스트를 불러오려 했을 때는 잘 되다가, 꼭 최신의 포스트만 안 되는 것 같습니다.

<img width="1464" alt="스크린샷 2023-05-09 오후 11 20 43" src="https://github.com/loosie/github-readme-tistory-card/assets/103521468/7d9c08f2-4e56-4053-82ae-f56773290bab">

이것은 [해당 깃허브의 README.md](https://github.com/loosie/github-readme-tistory-card)의 모습인데, 똑같이 엑박이 뜨고 있습니다.

처음에는 API Key가 만료되었나 싶었지만, 최신 포스트를 제외한 다른 포스트들은 모두 정상적으로 보여지는 것을 보니 그러한 문제는 아닌 것 같습니다.

원래는 원인을 해결해보고자 시도하였으나, 마땅한 해결 방법은 찾지 못 하여서, 대신 버그 제보로 대신합니다.

아래는 각각 실제 tistory card를 받아오게끔 시도하는 코드입니다.
두 번째는 직접 postId를 지정했습니다.

<img src="https://github-readme-tistory-card.vercel.app/api?name=nx006" alt="Tistory Post">
<img src="https://github-readme-tistory-card.vercel.app/api?name=nx006&postId=26" alt="Tistory Post">

**Comment by woon999** [comment]
티스토리 API 변경 사항이 있었을 수도 있겠네요 🤔 주말에 한번 확인해볼게요!

**Comment by jiholee0** [comment]
안녕하세요, 해당 이슈(엑스박스 버그)가 지난주부터 갑자기 또 발생한 것 같은데, 확인해주실 수 있을까요?
