### ISSUE TITLE
Tisory post card 관련 404

### ISSUE THREAD

**Issue by FeelingXD** [loosie/github-readme-tistory-card#5]
Tistory 포스트 카드 관련 api 요청시 -> `Error: Request failed with status code 404` 를 반환하고 있습니다.

**Comment by woon999** [comment]
https://notice.tistory.com/2664 티스토리에서 openAPI 지원을 종료한다고 합니다 🥲

**Comment by FeelingXD** [comment]
😭 그럼 이번 이슈는 .. 티스토리 문제군요.. 우선 감사합니다.
